{
 "title": "Capstone",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 22, "x": 0, "y": 0 },
   "options": { "content": "# Inventory" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Computers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(sec557.inventory.*.*)"
    }
   ]
  },
  {
   "title": "Total Servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(sec557.inventory.*.server)"
    }
   ]
  },
  {
   "title": "Total Workstations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(sec557.inventory.*.workstation)"
    }
   ]
  },
  {
   "title": "Inventory Detail",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "target": "aliasByNode(sec557.inventory.*.*, 2, 3)"
    },
    {
     "target": "alias(sumSeries(sec557.inventory.*.*), 'TOTAL')"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 22, "x": 0, "y": 14 },
   "options": { "content": "# Host Stats" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Risk Scores",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 16 },
   "targets": [
    {
     "target": "aliasByNode(averageSeries(sec557.hoststats.branchoffice.server.*.riskscore), 2, 3)"
    },
    {
     "target": "aliasByNode(averageSeries(sec557.hoststats.branchoffice.workstation.*.riskscore), 2, 3)"
    },
    {
     "target": "aliasByNode(averageSeries(sec557.hoststats.mainoffice.server.*.riskscore), 2, 3)"
    },
    {
     "target": "aliasByNode(averageSeries(sec557.hoststats.mainoffice.workstation.*.riskscore), 2, 3)"
    },
    {
     "target": "alias(averageSeries(sec557.hoststats.*.*.*.riskscore), 'AVERAGE')"
    }
   ]
  },
  {
   "title": "Risk Scores",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 16 },
   "targets": [
    {
     "target": "aliasByNode(sec557.hoststats.*.*.*.riskscore, 2, 3, 4)"
    }
   ]
  },
  {
   "title": "Average Risk Score",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "averageSeries(sec557.hoststats.*.*.*.riskscore)"
    }
   ]
  },
  {
   "title": "Critical Vulnerability Summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 24 },
   "targets": [
    {
     "target": "aliasByNode(sumSeries(sec557.hoststats.branchoffice.server.*.vuln.critical), 2, 3)"
    },
    {
     "target": "aliasByNode(sumSeries(sec557.hoststats.branchoffice.workstation.*.vuln.critical), 2, 3)"
    },
    {
     "target": "aliasByNode(sumSeries(sec557.hoststats.mainoffice.server.*.vuln.critical), 2, 3)"
    },
    {
     "target": "aliasByNode(sumSeries(sec557.hoststats.mainoffice.workstation.*.vuln.critical), 2, 3)"
    },
    {
     "target": "alias(sumSeries(sec557.hoststats.*.*.*.vuln.critical), 'TOTAL')"
    }
   ]
  },
  {
   "title": "Critical Vulnerabilities",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 24 },
   "targets": [
    {
     "target": "aliasByNode(sec557.hoststats.*.*.*.vuln.critical, 2, 3, 4)"
    }
   ]
  },
  {
   "title": "Total Critical Vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 18, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(sec557.hoststats.*.*.*.vuln.critical)"
    }
   ]
  },
  {
   "title": "Patch Lag Summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 32 },
   "targets": [
    {
     "target": "aliasByNode(averageSeries(sec557.hoststats.branchoffice.server.*.patchlag), 2, 3)"
    },
    {
     "target": "aliasByNode(averageSeries(sec557.hoststats.branchoffice.workstation.*.patchlag), 2, 3)"
    },
    {
     "target": "aliasByNode(averageSeries(sec557.hoststats.mainoffice.server.*.patchlag), 2, 3)"
    },
    {
     "target": "aliasByNode(averageSeries(sec557.hoststats.mainoffice.workstation.*.patchlag), 2, 3)"
    },
    {
     "target": "alias(averageSeries(sec557.hoststats.*.*.*.patchlag), 'AVERAGE')"
    }
   ]
  },
  {
   "title": "Patch Lag",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 32 },
   "targets": [
    {
     "target": "aliasByNode(sec557.hoststats.*.*.*.patchlag, 2, 3, 4)"
    }
   ]
  },
  {
   "title": "Average Patch Lag",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 18, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "averageSeries(sec557.hoststats.*.*.*.patchlag)"
    }
   ]
  },
  {
   "title": "Admin Counts",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 40 },
   "targets": [
    {
     "target": "aliasByNode(sec557.hoststats.*.*.*.admincount, 2, 3, 4)"
    }
   ]
  }
 ]
}